service: ${{ parameters.team }}-${{ parameters.name }}
useDotenv: true 
frameworkVersion: '2'
custom:
  wsgi:
    app: app.app


  datadog:
    site: 'datadoghq.eu'
    apiKey: '${DATADOG_API_KEY}'
    appKey: '${DATADOG_APP_KEY}'
    env: '${opt:stage, "dev"}'
    service: '${{ parameters.name }}-${opt:stage, "dev"}'
    version: '5.3.4'
    enableDDTracing: true
    enableDDLogs: true
    tags:
      - 'service:${{ parameters.name }}-${opt:stage, "dev"}'
      - 'env:${opt:stage, "dev"}'
      - 'team:${{ parameters.team }}'

provider:
  name: aws
  runtime: python3.9
  profile: dev
  region: eu-central-1
  stackTags:
        managed-by: serverless

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-datadog
